# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'noteAlix_shotDown.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(224, 168)
        MainWindow.setMinimumSize(QtCore.QSize(224, 168))
        MainWindow.setMaximumSize(QtCore.QSize(224, 168))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/noteAlix_shotDown.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(72, 58, 58);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(80, 30, 75, 23))
        self.pushButton.setStyleSheet("color: rgb(255, 179, 160);\n"
"font: 14pt \"Arial Narrow\";\n"
"border-radius:10px;\n"
"background-color: rgb(0, 0, 0);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(80, 60, 75, 23))
        self.pushButton_2.setStyleSheet("color: rgb(255, 179, 160);\n"
"font: 14pt \"Arial Narrow\";\n"
"border-radius:10px;\n"
"background-color: rgb(0, 0, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(80, 90, 75, 23))
        self.pushButton_3.setStyleSheet("color: rgb(255, 179, 160);\n"
"font: 14pt \"Arial Narrow\";\n"
"border-radius:10px;\n"
"background-color: rgb(0, 0, 0);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(80, 120, 75, 23))
        self.pushButton_4.setStyleSheet("color: rgb(255, 179, 160);\n"
"font: 14pt \"Arial Narrow\";\n"
"border-radius:10px;\n"
"background-color: rgb(0, 0, 0);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 10, 111, 16))
        self.label.setStyleSheet("color: rgb(255, 179, 160);")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "noteAlix_shotDown"))
        self.pushButton.setText(_translate("MainWindow", "0.5 HOUR"))
        self.pushButton_2.setText(_translate("MainWindow", "1 HOUR"))
        self.pushButton_3.setText(_translate("MainWindow", "1.5 HOUR"))
        self.pushButton_4.setText(_translate("MainWindow", "2 HOUR"))
        self.label.setText(_translate("MainWindow", "SHOTDOWN  IN  TIME "))
import icon_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
