# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Alix.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(259, 359)
        Form.setMinimumSize(QtCore.QSize(259, 359))
        Form.setMaximumSize(QtCore.QSize(259, 359))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/12.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("background-color: rgb(0, 0, 17);")
        self.one = QtWidgets.QPushButton(Form,clicked = lambda : self.press_it('1'))
        self.one.setGeometry(QtCore.QRect(20, 120, 41, 41))
        self.one.setStyleSheet("background-color: rgb(51, 0, 102);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:20px;\n"
"font: 14pt \"Arial\";\n"
"")
        self.one.setObjectName("one")
        self.two = QtWidgets.QPushButton(Form,clicked = lambda : self.press_it('2'))
        self.two.setGeometry(QtCore.QRect(70, 120, 41, 41))
        self.two.setStyleSheet("background-color: rgb(51, 0, 102);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:20px;\n"
"font: 14pt \"Arial\";\n"
"")
        self.two.setObjectName("two")
        self.three = QtWidgets.QPushButton(Form,clicked = lambda : self.press_it('3'))
        self.three.setGeometry(QtCore.QRect(120, 120, 41, 41))
        self.three.setStyleSheet("background-color: rgb(51, 0, 102);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:20px;\n"
"font: 14pt \"Arial\";\n"
"")
        self.three.setObjectName("three")
        self.six = QtWidgets.QPushButton(Form,clicked = lambda : self.press_it('6'))
        self.six.setGeometry(QtCore.QRect(120, 170, 41, 41))
        self.six.setStyleSheet("background-color: rgb(51, 0, 102);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:20px;\n"
"font: 14pt \"Arial\";\n"
"")
        self.six.setObjectName("six")
        self.five = QtWidgets.QPushButton(Form,clicked = lambda : self.press_it('5'))
        self.five.setGeometry(QtCore.QRect(70, 170, 41, 41))
        self.five.setStyleSheet("background-color: rgb(51, 0, 102);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:20px;\n"
"font: 14pt \"Arial\";\n"
"")
        self.five.setObjectName("five")
        self.four = QtWidgets.QPushButton(Form,clicked = lambda : self.press_it('4'))
        self.four.setGeometry(QtCore.QRect(20, 170, 41, 41))
        self.four.setStyleSheet("background-color: rgb(51, 0, 102);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:20px;\n"
"font: 14pt \"Arial\";\n"
"")
        self.four.setObjectName("four")
        self.seven = QtWidgets.QPushButton(Form,clicked = lambda : self.press_it('7'))
        self.seven.setGeometry(QtCore.QRect(20, 220, 41, 41))
        self.seven.setStyleSheet("background-color: rgb(51, 0, 102);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:20px;\n"
"font: 14pt \"Arial\";\n"
"")
        self.seven.setObjectName("seven")
        self.nine = QtWidgets.QPushButton(Form,clicked = lambda : self.press_it('9'))
        self.nine.setGeometry(QtCore.QRect(120, 220, 41, 41))
        self.nine.setStyleSheet("background-color: rgb(51, 0, 102);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:20px;\n"
"font: 14pt \"Arial\";\n"
"")
        self.nine.setObjectName("nine")
        self.eight = QtWidgets.QPushButton(Form,clicked = lambda : self.press_it('8'))
        self.eight.setGeometry(QtCore.QRect(70, 220, 41, 41))
        self.eight.setStyleSheet("background-color: rgb(51, 0, 102);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:20px;\n"
"font: 14pt \"Arial\";\n"
"")
        self.eight.setObjectName("eight")
        self.zero = QtWidgets.QPushButton(Form,clicked = lambda : self.press_it('0'))
        self.zero.setGeometry(QtCore.QRect(20, 270, 41, 41))
        self.zero.setStyleSheet("background-color: rgb(51, 0, 102);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:20px;\n"
"font: 14pt \"Arial\";\n"
"")
        self.zero.setObjectName("zero")
        self.help = QtWidgets.QPushButton(Form)
        self.help.setGeometry(QtCore.QRect(120, 330, 81, 21))
        self.help.setStyleSheet("background-color: rgb(51, 0, 102);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"font: 14pt \"Yu Gothic Light\";\n"
"")
        self.help.setObjectName("help")
        self.rbrackets = QtWidgets.QPushButton(Form,clicked = lambda : self.press_it(')'))
        self.rbrackets.setGeometry(QtCore.QRect(210, 190, 31, 91))
        self.rbrackets.setStyleSheet("background-color: rgb(51, 0, 102);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:15px;\n"
"font: 14pt \"Arial\";\n"
"")
        self.rbrackets.setObjectName("rbrackets")
        self.lbrackets = QtWidgets.QPushButton(Form,clicked = lambda : self.press_it('('))
        self.lbrackets.setGeometry(QtCore.QRect(210, 80, 31, 101))
        self.lbrackets.setStyleSheet("background-color: rgb(51, 0, 102);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:15px;\n"
"font: 14pt \"Arial\";\n"
"")
        self.lbrackets.setObjectName("lbrackets")
        self.clear = QtWidgets.QPushButton(Form,clicked = lambda : self.press_it('C'))
        self.clear.setGeometry(QtCore.QRect(20, 80, 61, 31))
        self.clear.setStyleSheet("background-color: rgb(51, 0, 102);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"font: 14pt \"Yu Gothic Light\";\n"
"")
        self.clear.setObjectName("clear")
        self.times = QtWidgets.QPushButton(Form,clicked = lambda : self.press_it('*'))
        self.times.setGeometry(QtCore.QRect(90, 80, 51, 31))
        self.times.setStyleSheet("background-color: rgb(51, 0, 102);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:15px;\n"
"font: 14pt \"Arial\";\n"
"")
        self.times.setObjectName("times")
        self.divided = QtWidgets.QPushButton(Form,clicked = lambda : self.press_it('/'))
        self.divided.setGeometry(QtCore.QRect(150, 80, 51, 31))
        self.divided.setStyleSheet("background-color: rgb(51, 0, 102);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:15px;\n"
"font: 14pt \"Arial\";\n"
"")
        self.divided.setObjectName("divided")
        self.plus = QtWidgets.QPushButton(Form,clicked = lambda : self.press_it('+'))
        self.plus.setGeometry(QtCore.QRect(170, 120, 31, 61))
        self.plus.setStyleSheet("background-color: rgb(51, 0, 102);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:15px;\n"
"font: 14pt \"Arial\";\n"
"")
        self.plus.setObjectName("plus")
        self.minus = QtWidgets.QPushButton(Form,clicked = lambda : self.press_it('-'))
        self.minus.setGeometry(QtCore.QRect(170, 190, 31, 61))
        self.minus.setStyleSheet("background-color: rgb(51, 0, 102);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:15px;\n"
"font: 14pt \"Arial\";\n"
"")
        self.minus.setObjectName("minus")
        self.rate = QtWidgets.QPushButton(Form,clicked = lambda : self.press_it('%'))
        self.rate.setGeometry(QtCore.QRect(170, 260, 31, 61))
        self.rate.setStyleSheet("background-color: rgb(51, 0, 102);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:15px;\n"
"font: 14pt \"Arial\";\n"
"")
        self.rate.setObjectName("rate")
        self.about = QtWidgets.QPushButton(Form)
        self.about.setGeometry(QtCore.QRect(20, 330, 81, 21))
        self.about.setStyleSheet("background-color: rgb(51, 0, 102);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"font: 14pt \"Yu Gothic Light\";\n"
"")
        self.about.setObjectName("about")
        self.eyler = QtWidgets.QPushButton(Form,clicked = lambda : self.press_it('2.7'))
        self.eyler.setGeometry(QtCore.QRect(70, 270, 41, 41))
        self.eyler.setStyleSheet("background-color: rgb(51, 0, 102);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:20px;\n"
"font: 14pt \"Arial\";\n"
"")
        self.eyler.setObjectName("eyler")
        self.pi = QtWidgets.QPushButton(Form,clicked = lambda : self.press_it('3.14'))
        self.pi.setGeometry(QtCore.QRect(120, 270, 41, 41))
        self.pi.setStyleSheet("background-color: rgb(51, 0, 102);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:20px;\n"
"font: 14pt \"Arial\";\n"
"")
        self.pi.setObjectName("pi")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 30, 221, 31))
        self.label.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"font: 25 20pt \"Segoe UI Light\";\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.rate_2 = QtWidgets.QPushButton(Form,clicked = lambda : self.math_it())
        self.rate_2.setGeometry(QtCore.QRect(210, 290, 31, 61))
        self.rate_2.setStyleSheet("background-color: rgb(51, 0, 102);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:15px;\n"
"font: 14pt \"Arial\";\n"
"")
        self.rate_2.setObjectName("rate_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Alix"))
        self.one.setText(_translate("Form", "1"))
        self.two.setText(_translate("Form", "2"))
        self.three.setText(_translate("Form", "3"))
        self.six.setText(_translate("Form", "6"))
        self.five.setText(_translate("Form", "5"))
        self.four.setText(_translate("Form", "4"))
        self.seven.setText(_translate("Form", "7"))
        self.nine.setText(_translate("Form", "9"))
        self.eight.setText(_translate("Form", "8"))
        self.zero.setText(_translate("Form", "0"))
        self.help.setText(_translate("Form", "Help"))
        self.rbrackets.setText(_translate("Form", ")"))
        self.lbrackets.setText(_translate("Form", "("))
        self.clear.setText(_translate("Form", "Clear"))
        self.times.setText(_translate("Form", "x"))
        self.divided.setText(_translate("Form", "/"))
        self.plus.setText(_translate("Form", "+"))
        self.minus.setText(_translate("Form", "-"))
        self.rate.setText(_translate("Form", "%"))
        self.about.setText(_translate("Form", "About"))
        self.eyler.setText(_translate("Form", "e"))
        self.pi.setText(_translate("Form", "π"))
        self.label.setText(_translate("Form", "0"))
        self.rate_2.setText(_translate("Form", "="))
    def math_it(self):
        screen = self.label.text()
        answer = eval(screen)
        self.label.setText(str(answer))

    def press_it(self,pressed):
        if pressed == 'C':
            self.label.setText('0')
        else:
            if self.label.text() == '0':
                self.label.setText('')
            self.out = self.label.setText(f'{self.label.text()}{pressed}')
            print(self.out)



import image_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
